trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildJob
        displayName: Maven Build
        steps:
          - task: Maven@4
            displayName: mvn package
            inputs:
              mavenPomFile: pom.xml
              goals: package
              options: -DskipTests
              publishJUnitResults: false
