trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: BuildJob
        displayName: Maven Build
        steps:
          - task: JavaToolInstaller@0
            displayName: Use JDK 21
            inputs:
              versionSpec: '21'
              jdkArchitectureOption: x64
              jdkSourceOption: PreInstalled
          - task: Maven@4
            displayName: mvn package
            inputs:
              mavenPomFile: pom.xml
              goals: package
              options: -DskipTests
              publishJUnitResults: false
              jdkVersionOption: '1.21'
