apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  description: ${{ values.description }}
  annotations:
    dev.azure.com/host-org: dev.azure.com/${{ values.adoOrg }}
    dev.azure.com/project: ${{ values.adoProject }}
    dev.azure.com/build-definition: ${{ values.adoOrg }}.${{ values.appName }}
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
